# Datawrapper configuration
#

domain: datawrapper.de
chart_domain: c.datawrapper.de

# show debug message?
debug: true

# some default values
default_theme: default
default_vis: bar-chart

# thumbnail sizes [width, height]
thumbnails:
    s: [150, 150]
    m: [260, 170]

# email address for admin
admin_email: hello@datawrapper.de
log_email: debug@datawrapper.de

# analytics
analytics:
    type: Piwik
    config:
        url: piwik.datawrapper.de  # without http:// and trailing slash
        idSite: 5


# uncomment this if your Datawrapper is locked behind HTTP Authentication
# http_auth: username:password